# this file is always loaded. This is the default profile, it's always active
db:
    login: my-login
    password: my-password
    url: my-db:login:password@port:my-db
management:
    endpoints:
        web:
            exposure:
                include: '*'
movie-db:
    api-key: cc00f48e03cb6a988c162313366287c9
my-list-values-variable: One,Two,Three
my-map-values-variable: '{1:''One'',2:''Two'',3:''Three''}'
server:
    port: 8081
spring:
    application:
        name: movie-info-service # the name here must be the name of the config yml file in the config server

    config:
        import: "configserver:http://localhost:8080"
